struct Constants {
    static let membersAutocomplete = [
        "Luke Skywalker",
        "Lady Gaga",
        "The Weeknd",
        "Margit",
        "Goldfrey",
        "Malenia",
        "Rennala",
        "Blaidd",
        "Rykard",
        "Mohg",
        "Godrick",
        "Loretta",
        "Maliketh",
        "Hoarah Loux",
        "Walter White",
        "Jesse Pinkman",
        "Joey Tribbiani",
        "Rachel Green",
        "Ross Geller",
        "José Brandão",
        "Vinicius Torres",
        "Thais Couto",
        "João Almeida",
        "Rodrigo Barbosa",
        "Kratos",
        "Atreus",
        "Fox",
        "Billie Eilish",
        "Katy Perry",
        "Rosalia",
        "Alex Turner"
    ]
}
